# Site settings
title: Vy Cu
subtitle: "Vy Cu's Mental Model"
email: vy.hoang.cu@gmail.com
description: "Software Engineer in San Francisco"
baseurl: ""
url: "http://veeweeherman.github.io"
twitter_username: "veeweeherman"
github_username:  "veeweeherman"
instagram_username: ""

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
