name:               "Vy"
blog_title:         "Inner Workings of a Puzzling Mind"
description:        "Software Engineer in San Francisco"

url:                ""
author:             "veeweeherman"
email:              "vy.hoang.cu@gmail.com"
avatar:             "/images/camel_mongolia_profile_pic.jpg"
twitter:            "veeweeherman"
email:              "jhondoe@abc.com"
github:             "veeweeherman"
linkedin:           "vyhcu"

disqus_shortname:   "veeweehermangithubio"

favicon:            "/images/favicon.ico"
background:         "/images/jellyfish.jpg"

paginate:           4
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  # - name:           "Download"
  #   href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
